"""
[Phase 4 - 升級 J] PSD 自動組裝 2.0
進階圖層分組、混合模式指派與一鍵導出
"""

import json
from pathlib import Path
from typing import Dict, List

class PSDAutoAssembly:
    """智能 PSD 圖層管理與組裝"""
    
    def __init__(self):
        self.blend_mode_rules = {
            "VFX": "Screen",
            "Glow": "Screen",
            "Light": "Screen",
            "Particle": "Screen",
            "Shadow": "Multiply",
            "Darken": "Multiply",
            "Symbol": "Normal",
            "UI": "Normal",
            "Background": "Normal"
        }
        
        self.layer_groups = {
            "High_Payout": ["Wild", "Scatter", "M1", "M2", "M3"],
            "Medium_Payout": ["M4", "M5", "M6"],
            "Low_Payout": ["A", "K", "Q", "J", "10", "9"],
            "Effects": ["VFX", "Glow", "Particle", "Shadow"],
            "UI_Elements": ["UI", "Frame", "Button"],
            "Background_Layers": ["BG", "Background"]
        }
        
        # [V3.0] 通用版型常數 (Portrait 1080x1920 標準)
        self.PORTRAIT_CANVAS = (1080, 1920)
        self.UI_ANCHORS = {
            "Header": (540, 200),
            "Base": (540, 1720),
            "Pillar_Left": (50, 960),
            "Pillar_Right": (1030, 960)
        }
        
        # 3x5 符號柵格座標 (中心點)
        self.REEL_GRID = []
        start_x, start_y = 140, 600
        dx, dy = 200, 220
        for r in range(3):
            for c in range(5):
                self.REEL_GRID.append((start_x + c * dx, start_y + r * dy))
    
    def generate_psd_structure(self, asset_list: List[Dict]) -> Dict:
        """
        Generate PSD layer structure from asset list
        
        Args:
            asset_list: List of dicts with 'name', 'type', 'path', 'variant'
            
        Returns:
            PSD structure dict ready for JSX script
        """
        structure = {
            "canvas_size": self.PORTRAIT_CANVAS, # 強制使用直立版型
            "groups": {},
            "layers": []
        }
        
        symbol_count = 0
        # Organize assets into groups and assign fixed coordinates
        for asset in asset_list:
            group_name = self._determine_group(asset)
            blend_mode = self._determine_blend_mode(asset)
            
            # [V3.0] 座標柵格分配邏輯
            pos = (540, 960) # 預設置中
            asset_type = asset.get("type", "").upper()
            asset_name = asset.get("name", "").upper()
            
            if "SYMBOL" in asset_type or "M1" in asset_name:
                if symbol_count < len(self.REEL_GRID):
                    pos = self.REEL_GRID[symbol_count]
                    symbol_count += 1
            elif "HEADER" in asset_name:
                pos = self.UI_ANCHORS["Header"]
            elif "BASE" in asset_name:
                pos = self.UI_ANCHORS["Base"]
            elif "PILLAR" in asset_name:
                if "LEFT" in asset_name or "_L" in asset_name:
                     pos = self.UI_ANCHORS["Pillar_Left"]
                else:
                     pos = self.UI_ANCHORS["Pillar_Right"]
            elif "MASCOT" in asset_name:
                pos = (200, 1200) # 吉祥物固定左側位置
            
            layer_info = {
                "name": asset.get("name", "Unnamed"),
                "path": asset.get("path"),
                "type": asset.get("type"),
                "variant": asset.get("variant", "Idle"),
                "blend_mode": blend_mode,
                "group": group_name,
                "position": pos, # [V3.0] 固定座標
                "visible": True,
                "opacity": 100
            }
            
            # Add to structure
            if group_name not in structure["groups"]:
                structure["groups"][group_name] = []
            
            structure["groups"][group_name].append(layer_info)
            structure["layers"].append(layer_info)
        
        return structure
    
    def generate_jsx_script(self, psd_structure: Dict, output_path: str) -> str:
        """
        Generate Photoshop JSX script for auto-assembly
        
        Args:
            psd_structure: Structure from generate_psd_structure()
            output_path: Where to save the PSD file
            
        Returns:
            JSX script as string
        """
        jsx_template = '''
// Auto-generated PSD Assembly Script (Phase 4 - Upgrade J)
// Generated by GameAssetWorkshop Production Intelligence

var doc = app.documents.add({canvas_width}, {canvas_height}, 72, "AutoAssembled_Slot", NewDocumentMode.RGB);

// Create layer groups
{group_creation}

// Import and place layers
{layer_placement}

// Apply blend modes
{blend_modes}

// Save document
var saveFile = new File("{output_path}");
var psdOptions = new PhotoshopSaveOptions();
psdOptions.layers = true;
doc.saveAs(saveFile, psdOptions);

alert("PSD Assembly Complete!");
'''
        
        # Generate group creation code
        group_code = []
        for group_name in psd_structure["groups"].keys():
            group_code.append(f'var group_{group_name} = doc.layerSets.add();')
            group_code.append(f'group_{group_name}.name = "{group_name}";')
        
        # Generate layer placement code
        layer_code = []
        for i, layer in enumerate(psd_structure["layers"]):
            layer_code.append(f'// Layer {i+1}: {layer["name"]}')
            layer_path_escaped = layer["path"].replace("\\\\", "\\\\\\\\")
            layer_code.append(f'var file_{i} = new File("{layer_path_escaped}");')
            layer_code.append(f'var layer_{i} = app.open(file_{i});')
            layer_code.append(f'layer_{i}.selection.selectAll();')
            layer_code.append(f'layer_{i}.selection.copy();')
            layer_code.append(f'layer_{i}.close(SaveOptions.DONOTSAVECHANGES);')
            # [V3.0] 移動圖層至指定座標
            pos_x, pos_y = layer["position"]
            layer_code.append(f'doc.activeLayer.translate({pos_x}, {pos_y});')
            layer_code.append(f'doc.activeLayer.move(group_{layer["group"]}, ElementPlacement.INSIDE);')
        
        # Generate blend mode code
        blend_code = []
        for i, layer in enumerate(psd_structure["layers"]):
            blend_mode = layer["blend_mode"]
            jsx_blend = self._blend_mode_to_jsx(blend_mode)
            blend_code.append(f'// Set blend mode for {layer["name"]}')
            blend_code.append(f'doc.layers.getByName("{layer["name"]}").blendMode = {jsx_blend};')
        
        # Fill template
        jsx_script = jsx_template.format(
            canvas_width=psd_structure["canvas_size"][0],
            canvas_height=psd_structure["canvas_size"][1],
            group_creation="\n".join(group_code),
            layer_placement="\n".join(layer_code),
            blend_modes="\n".join(blend_code),
            output_path=output_path.replace("\\", "\\\\")  # Escape backslashes
        )
        
        return jsx_script
    
    def export_assembly_config(self, psd_structure: Dict, output_path: str):
        """Export PSD structure as JSON for inspection"""
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(psd_structure, f, indent=2, ensure_ascii=False)
    
    def _determine_group(self, asset: Dict) -> str:
        """Determine which group an asset belongs to"""
        asset_name = asset.get("name", "")
        asset_type = asset.get("type", "")
        
        # Check each group's patterns
        for group_name, patterns in self.layer_groups.items():
            for pattern in patterns:
                if pattern in asset_name or pattern in asset_type:
                    return group_name
        
        return "Other"
    
    def _determine_blend_mode(self, asset: Dict) -> str:
        """Determine appropriate blend mode for asset"""
        asset_name = asset.get("name", "")
        asset_type = asset.get("type", "")
        
        # Check blend mode rules
        for keyword, mode in self.blend_mode_rules.items():
            if keyword in asset_name or keyword in asset_type:
                return mode
        
        return "Normal"
    
    def _blend_mode_to_jsx(self, blend_mode: str) -> str:
        """Convert blend mode name to JSX constant"""
        jsx_modes = {
            "Normal": "BlendMode.NORMAL",
            "Screen": "BlendMode.SCREEN",
            "Multiply": "BlendMode.MULTIPLY",
            "Overlay": "BlendMode.OVERLAY"
        }
        return jsx_modes.get(blend_mode, "BlendMode.NORMAL")

# Testing
if __name__ == "__main__":
    assembler = PSDAutoAssembly()
    
    print("🎨 PSD Auto-Assembly 2.0 - Test Suite")
    print("=" * 60)
    
    # Test 1: Create sample asset list
    print("\n[Test 1] Generating PSD Structure")
    test_assets = [
        {"name": "Symbol_M1_Idle", "type": "Symbol", "path": "output/Symbol_M1_Idle.png", "variant": "Idle"},
        {"name": "Symbol_M1_Win", "type": "Symbol", "path": "output/Symbol_M1_Win.png", "variant": "Win"},
        {"name": "VFX_Glow", "type": "VFX", "path": "output/VFX_Glow.png"},
        {"name": "Shadow", "type": "Shadow", "path": "output/Shadow.png"},
        {"name": "UI_Frame", "type": "UI", "path": "output/UI_Frame.png"},
    ]
    
    structure = assembler.generate_psd_structure(test_assets)
    print(f"  Total Layers: {len(structure['layers'])}")
    print(f"  Total Groups: {len(structure['groups'])}")
    
    # Test 2: Show layer organization
    print("\n[Test 2] Layer Organization")
    for group_name, layers in structure["groups"].items():
        print(f"  📁 {group_name}:")
        for layer in layers:
            print(f"    - {layer['name']} (Blend: {layer['blend_mode']})")
    
    # Test 3: Generate JSX script
    print("\n[Test 3] JSX Script Generation")
    jsx_script = assembler.generate_jsx_script(structure, "output/AutoAssembled.psd")
    print(f"  ✓ Generated {len(jsx_script)} characters of JSX code")
    
    # Save JSX for inspection
    jsx_path = Path("test_output_phase4/auto_assembly.jsx")
    jsx_path.parent.mkdir(exist_ok=True)
    with open(jsx_path, 'w', encoding='utf-8') as f:
        f.write(jsx_script)
    print(f"  ✓ Saved to: {jsx_path}")
    
    # Test 4: Export config
    print("\n[Test 4] Export Assembly Config")
    config_path = Path("test_output_phase4/psd_structure.json")
    assembler.export_assembly_config(structure, str(config_path))
    print(f"  ✓ Config saved to: {config_path}")
    
    print("\n" + "=" * 60)
    print("✅ All tests completed!")
