import cv2
import numpy as np
import os
import argparse
import sys
from rembg import remove
from PIL import Image
import io

print("Script started.", flush=True)

def generate_jsx(output_dir, parts_info, original_width, original_height, jsx_path):
    print(f"Generating JSX at {jsx_path}...", flush=True)
    layers_js = []
    
    # Sort parts by size (largest at bottom/first imported?)
    # Photoshop adds new layers on top.
    # Usually we want background (largest) at bottom, but here we just have parts.
    
    for part in parts_info:
        fpath = os.path.abspath(part['path']).replace("\\", "/")
        name = part['name']
        x = part['x']
        y = part['y']
        
        layers_js.append(f"""
    (function() {{
        var fileRef = new File("{fpath}");
        if (fileRef.exists) {{
            var doc = app.activeDocument;
            var layer = doc.artLayers.add();
            layer.name = "{name}";
            
            var tempDoc = open(fileRef);
            tempDoc.selection.selectAll();
            tempDoc.selection.copy();
            tempDoc.close(SaveOptions.DONOTSAVECHANGES);
            
            doc.paste();
            var activeLayer = doc.activeLayer;
            activeLayer.name = "{name}";
            
            var bounds = activeLayer.bounds; 
            var currentLeft = bounds[0].value;
            var currentTop = bounds[1].value;
            
            var deltaX = {x} - currentLeft;
            var deltaY = {y} - currentTop;
            
            activeLayer.translate(deltaX, deltaY);
        }}
    }})();
        """)

    jsx_content = f"""
// Auto-generated by smart_slicer.py
#target photoshop

function main() {{
    var originalWidth = {original_width};
    var originalHeight = {original_height};
    
    var docName = "Split_Import";
    var doc = app.documents.add(originalWidth, originalHeight, 72, docName, NewDocumentMode.RGB, DocumentFill.TRANSPARENT);
    
    {chr(10).join(layers_js)}
    
    alert("Import complete! Imported {len(layers_js)} layers.");
}}

main();
"""
    with open(jsx_path, 'w', encoding='utf-8') as f:
        f.write(jsx_content)
    print("JSX generated.", flush=True)

def slice_image(image_path, grid_json=None):
    output_dir = None
    
    if not os.path.exists(image_path):
        print(f"Error: File not found {image_path}", flush=True)
        return

    print(f"Loading image: {image_path}", flush=True)
    image_name = os.path.splitext(os.path.basename(image_path))[0]

    try:
        with open(image_path, 'rb') as i:
            input_data = i.read()
            print("Running AI background removal (rembg)...", flush=True)
            output_data = remove(input_data)
            print("Background removed.", flush=True)
            
        pil_img = Image.open(io.BytesIO(output_data))
        img_rgba = np.array(pil_img)
        
        if img_rgba.shape[2] == 3:
            img_rgba = cv2.cvtColor(img_rgba, cv2.COLOR_RGB2RGBA)
            
    except Exception as e:
        print(f"Error during AI background removal: {e}", flush=True)
        return

    original_h, original_w = img_rgba.shape[:2]
    alpha = img_rgba[:, :, 3]
    
    # OUTPUT DIR
    output_dir = os.path.join(r"D:\AG\GameAssetWorkshop", "output", image_name + "_parts_ai")
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    parts_info = []
    
    # 1. 處理 Grid (5x3) 如果存在
    if grid_json:
        try:
            import json
            g = json.loads(grid_json)
            s_size = g.get('symbol_size', 160)
            spacing = g.get('spacing', 10)
            startX = g.get('grid_startX', 220)
            startY = g.get('grid_startY', 110)
            cols = g.get('columns', 5)
            rows = g.get('rows', 3)
            
            # 適配比例
            scaleX = original_w / 1280.0
            scaleY = original_h / 720.0
            
            print(f"Grid Cutting: {cols}x{rows} symbols...", flush=True)
            for r in range(rows):
                for c in range(cols):
                    x = int((startX + c * (s_size + spacing)) * scaleX)
                    y = int((startY + r * (s_size + spacing)) * scaleY)
                    w = int(s_size * scaleX)
                    h = int(s_size * scaleY)
                    
                    # 進行切割
                    roi = img_rgba[y:y+h, x:x+w]
                    # 只有當區域內有足夠像素時才儲存 (避免切到全透明)
                    if np.mean(roi[:,:,3]) > 5:
                        p_name = f"Symbol_{c}_{r}.png"
                        p_path = os.path.join(output_dir, p_name)
                        Image.fromarray(roi).save(p_path)
                        
                        parts_info.append({
                            "name": f"Symbol_{c}_{r}",
                            "path": p_path,
                            "x": x, "y": y, "w": w, "h": h
                        })
                        
                        # 從 Mask 中移除已切除區域，避免重複識別
                        alpha[y:y+h, x:x+w] = 0
            
        except Exception as ge:
            print(f"Grid extraction failed: {ge}", flush=True)

    # 2. 處理剩餘的 UI 島嶼 (如 Jackpot, Buttons)
    _, thresh = cv2.threshold(alpha, 10, 255, cv2.THRESH_BINARY)
    kernel = np.ones((3,3), np.uint8)
    thresh = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)
    
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    print(f"Found {len(contours)} additional UI components.", flush=True)

    for idx, cnt in enumerate(contours):
        x, y, w, h = cv2.boundingRect(cnt)
        if w * h < 500: continue # 過濾雜點
            
        roi = img_rgba[y:y+h, x:x+w]
        p_name = f"UI_Part_{idx:03d}.png"
        p_path = os.path.join(output_dir, p_name)
        
        Image.fromarray(roi).save(p_path)
        parts_info.append({
            "name": f"UI_Part_{idx}",
            "path": p_path,
            "x": x, "y": y, "w": w, "h": h
        })
        
    # Export parts info to JSON for AI Creator
    import json
    json_path = os.path.join(output_dir, "parts.json")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(parts_info, f, indent=4)
    print(f"Saved {len(parts_info)} total parts to {output_dir}", flush=True)
    
    jsx_path = os.path.join(r"D:\AG\GameAssetWorkshop\output", "import_layers_ai.jsx")
    generate_jsx(output_dir, parts_info, original_w, original_h, jsx_path)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("image_path")
    parser.add_argument("--grid", help="JSON string for grid layout")
    args = parser.parse_args()
    
    if args.image_path:
        slice_image(args.image_path, args.grid)
    else:
        print("No image path provided", flush=True)
